### PR TITLE
Update findup-sync to v0.4.0.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by shama** [comment]
This version looks like [a big change](https://github.com/js-cli/node-findup-sync/commit/93cf4a65ca4892ca72fe864c1b9e90839f836c38). Do you know if it's fully backwards compatible?

**Comment by XhmikosR** [comment]
We just search for a specific string, `'lib/grunt.js'` so that shouldn't be affected.

But I couldn't manage to get to inside the `catch` to actually see the result.

**Comment by shama** [comment]
Cool, I'll take a look into it more.

I'm not sure what you use for development/debugging but I use [devtool](https://www.npmjs.com/package/devtool). `npm i devtool -g` and then `devtool ./node_modules/.bin/grunt`. Then add `debugger` statements where I want to pause execution. That should let you pause before a catch and see the result.

**Comment by jonschlinkert** [comment]
> Do you know if it's fully backwards compatible?

fwiw, it passes all of the original unit tests plus additional unit tests. not sure how helpful that is given the size of grunt's user base. I'll leave that to your expertise

**Pull request closed without merging**
